export const INIT_FETCHING = 'INIT_FETCHING';
export const INIT_FETCHING_PENDING = 'INIT_FETCHING_PENDING';
export const INIT_FETCHING_FULFILLED = 'INIT_FETCHING_FULFILLED';
export const INIT_FETCHING_REJECTED = 'INIT_FETCHING_REJECTED';
